source 'https://rubygems.org'	

gem 'jekyll'	
gem "nokogiri", ">= 1.10.4"	
gem 'addressable'	
gem 'jekyll-feed'	
gem 'jekyll-environment-variables'	
gem 'jekyll-github-metadata'	
gem 'jekyll-scholar'	
gem 'jekyll-sitemap'	
gem 'jekyll-redirect-from'	
gem 'jekyll-last-modified-at'	
gem 'csl-styles'	
gem 'awesome_bot'	
gem 'html-proofer'	
gem 'pkg-config'	
gem 'kwalify'
gem 'kramdown', '1.17.0'
gem 'faraday', '0.17.1'	
gem 'jekyll_pages_api_search'
